import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container:{
        flex:1,
        justifyContent:'center',
        alignItems:'center'
    },
    titulo:{
        fontSize:30,
        marginLeft:10,
        marginTop:10,
        marginBottom:30
    },
    imgbackground:{
        flex:1,
        width:"100%",
        resizeMode:'cover'
    },
    imgavatar:{
        width:400,
        height:400,
        resizeMode:"cover",
        marginTop:100,
        marginLeft:-50
    },

    areaacesso:{
        width:"100%",
        height:550,
        backgroundColor:"#fff",
        zIndex:1000,
        marginTop:-230,
        borderTopLeftRadius:30,
        borderTopRightRadius:30
    },
    label:{
        fontSize:15,
        paddingLeft:30
    },
    txtlogin:{
        marginLeft:30,
        borderBottomWidth:1,
        borderBottomColor:"#ccc",
        width:"85%",
        marginBottom:20
    },
    txtsenha:{
        marginLeft:30,
        borderBottomWidth:1,
        borderBottomColor:"#ccc",
        width:"85%",
        marginBottom:20,
        paddingTop:10
    },
    txtnomecompleto:{
        marginLeft:30,
        borderBottomWidth:1,
        borderBottomColor:"#ccc",
        width:"85%",
        marginBottom:20,
        paddingTop:10
    },
    txtemail:{
        marginLeft:30,
        borderBottomWidth:1,
        borderBottomColor:"#ccc",
        width:"85%",
        marginBottom:20,
        paddingTop:10
    },
    txtcpf:{
        marginLeft:30,
        borderBottomWidth:1,
        borderBottomColor:"#ccc",
        width:"85%",
        marginBottom:20,
        paddingTop:10
    },
    txtfoto:{
        marginLeft:30,
        borderBottomWidth:1,
        borderBottomColor:"#ccc",
        width:"85%",
        marginBottom:20,
        paddingTop:10
    },
    btnlogin:{
        backgroundColor:"teal",
        width:280,
        padding:10,
        borderRadius:20,
        marginLeft:"auto",
        marginRight:"auto",
        marginTop:30
    },
    txtbtnlogin:{
        color:"#fff",
        textAlign:"center",
        fontSize:15
    },
    btnrecuperarsenha:{
        padding:5
    },
    txtrecuperarsenha:{
        color:"#000",
        textAlign:"right",
        marginRight:15,
        marginTop:-10
    },
    btncadastrar:{
        marginTop:30,
        paddingTop:20,
        borderTopWidth:1,
        borderTopColor:"#ddd",
        width:"80%",
        marginRight:"auto",
        marginLeft:"auto"
    },

    txtbtncadastrar:{
        fontSize:12,
        textAlign:"center"
    },

    superior:{
        backgroundColor:"teal",
        width:"100%",
        paddingTop:40,
        paddingBottom:15,
        position:"absolute",
        top:0
    },

    txtsuperior:{
        color:"#fff",
        textAlign:"center",
        fontSize:20
    },
    imgproduto:{
        width:"100%",
        height:200,
        resizeMode:"contain"
    },

    scrollviewhome:{
        backgroundColor:"#fff",
        width:"100%",
        padding:10,
        position:"absolute",
        top:280,
        height:500
  
    },
    listaprodutos:{
        flexDirection:"row",
        flexWrap:"wrap"
    },
    itemproduto:{
        borderColor:"#eee",
        borderWidth:1,
        width:"45%",
        margin:6,
        justifyContent:"center",
        alignItems:"center"
        
    },
    nomeproduto:{
        fontSize:15,
        fontWeight:"bold"
    },
    preco:{
        fontSize:15,
        color:"#f00"
    },
    btncomprar:{
        backgroundColor:"teal",
        padding:10,
        margin:10
    },
    txtbtncomprar:{
        color:"#fff",
        fontSize:15
    },
    grupoimgdetalhe:{
        flexDirection:"row"
    },

    imgdetalhe:{
        width:400,
        height:300,
        margin:5,
        resizeMode:"cover"
    },

    scrollviewdetalhe:{
        flex:1
    },
    infoproduto:{
        flex:1
    },

    btnpagamento:{
        backgroundColor:"#f00",
        padding:10,
        borderRadius:50,
        marginTop:50
    }
    ,
    txtbtnpagamento:{
        color:"#fff",
        fontWeight:"bold",
        fontSize:15
    },
    tipopagamento:{
        width:"80%",
        backgroundColor:"#fff",
        marginBottom:10,
        borderColor:"#fff",
        marginLeft:"auto",
        marginRight:"auto"
    },
    controle:{
        width:"80%",
        backgroundColor:"#fff",
        padding:10,
        marginBottom:10,
    }


})